### ISSUE TITLE
Failed to get process info for promscale container process

### ISSUE THREAD

**Issue by nascentcore-eng** [tricorder-observability/Starship#3]
```
kubectl create ns tricorder
helm install my-starship tricorder-stable/starship -n tricorder
```
Then take a look at the logs of one of the agent that colocate with the promscale instance.
Saw that the promscale container's process cannot be found

![image](https://user-images.githubusercontent.com/112656580/219306138-0ac73cfa-8832-496a-8446-56b7ac0e488f.png)

![image](https://user-images.githubusercontent.com/112656580/219306405-34054b52-d63f-425e-b368-aa84770f5dfc.png)

**Comment by jmzwcn** [comment]
This is because this pod was restarted repeatly and didn't run with real PID.

![screenshot-20230217-183705](https://user-images.githubusercontent.com/11627425/219621268-ebfc1820-29c5-4dd5-a19c-eeca8afb64d0.png)
![screenshot-20230217-183622](https://user-images.githubusercontent.com/11627425/219621274-c823a50b-1715-4a1f-aa96-1552d5fad6a0.png)

**Comment by jmzwcn** [comment]
Have merged in https://github.com/tricorder-observability/starship/pull/46.
